name: AoD
version: 0.0.1
description: Army of Darkness plugin
author: Mmarz11
main: me.mmarz11.aod.AoD
commands:
  killmobs:
    usage: /killmobs
    description: Kills all mobs
  bow:
    usage: /bow <lore>
    description: Gives an explosive bow
  setlobbytime:
    usage: /setlobbytime <time>
    description: Sets the lobby timer
  setbuildtime:
    usage: /setbuildtime <time>
    description: Sets the build timer
  endround:
    usage: /endround
    description: Ends the round
  brains:
    usage: /brains
    description: Tells player number of brains they possess